channels:
- pytorch
- nvidia
- conda-forge
dependencies:
- python=3.11.0
- pip<=23.2.1
- langchain==0.3.7
- pytorch::faiss-gpu
- huggingface_hub
- pypdf
- bitsandbytes
- pydantic
- transformers
- pytorch::pytorch
- pytorch::torchvision
pip:
  - langchain-huggingface
  - langchain-community
name: mlflow-env
