catalog: main 
db: jcmodels
llm_model_serving_endpoint_name: databricks-dbrx-instruct
vector_search_endpoint_name: dbdemos_vs_endpoint
vector_search_source_table_name: databricks_documentation
vector_search_index_table_name: databricks_documentation_vs_index
llm_prompt_template: "You are an assistant that answers questions. Use the following
  pieces of retrieved context to answer the question. Some pieces of context may be
  irrelevant, in which case you should not use them to form the answer.\n\nContext:
  {context}"
MODEL_NAME_FQN: main.jcmodels.basic_rag_demo
DATABRICKS_SITEMAP_URL: https://docs.databricks.com/en/doc-sitemap.xml